# Site settings
title: Jeremiah Stanley
email: miah@miah.org
description: > # this means to ignore newlines until "baseurl:"
 They seriously just let you post anything you want on the internet?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://miahorg.github.io" # the base hostname & protocol for your site
twitter_username: miahorg
github_username:  miahorg

# Build settings
markdown: kramdown

# Set the timezone for delayed posting calculations
timezone: America/Denver